{{ cookiecutter.project_slug }}/src/{{ cookiecutter.project_slug }}/billing/urls.py
from django.urls import path
from {{cookiecutter.project_slug}}.billing import views

app_name = "{{ cookiecutter.project_slug }}-billing"

urlpatterns = [
    path("settings/billing/", views.billing_settings_view, name="billing-settings"),
    path(
        "billing/subscribe-checkout/create/",
        views.create_subscribe_checkout_view,
        name="create-subscribe-checkout",
    ),
    path(
        "billing/cancel-subscription/",
        views.cancel_subscription_view,
        name="cancel-subscription",
    ),
    path(
        "billing/reactivate-subscription/",
        views.reactivate_subscription_view,
        name="reactivate-subscription",
    ),
    path("billing/stripe/webhook/", views.stripe_webhook_view, name="stripe-webhook"),
]

{{ cookiecutter.project_slug }}/src/{{ cookiecutter.project_slug }}/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from {{cookiecutter.project_slug}} import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.index_view, name="index"),
    path("", include("{{ cookiecutter.project_slug }}.auth.urls")),
    path("", include("{{ cookiecutter.project_slug }}.billing.urls")),
]

if settings.DEBUG is True:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
        path("__reload__/", include("django_browser_reload.urls")),
    ]

{{ cookiecutter.project_slug }}/src/{{ cookiecutter.project_slug }}/billing/models.py
from django.db import models


class StripeCustomer(models.Model):
    user = models.OneToOneField(
        "{{ cookiecutter.project_slug }}_auth.User",
        related_name="stripe_customer",
        on_delete=models.CASCADE,
    )
    stripe_customer_id = models.CharField(max_length=255)
    stripe_subscription_id = models.CharField(max_length=255)

{{ cookiecutter.project_slug }}/src/{{ cookiecutter.project_slug }}/billing/forms.py
from django import forms
from django_countries.fields import CountryField


class UpdateBillingInformationForm(forms.Form):
    template_name = "billing/forms/update_billing_information_form.html"
    name = forms.CharField(
        max_length=255,
        label="Name",
        error_messages={"required": "You need to enter your name."},
        help_text="Your full name",
        widget=forms.TextInput(),
        required=True,
    )
    address_line_1 = forms.CharField(
        max_length=255,
        label="Address",
        help_text="P.O box, company name, c/o",
        widget=forms.TextInput(),
        required=True,
    )
    address_line_2 = forms.CharField(
        max_length=255,
        label="Address line 2",
        help_text="Apartment, suite, unit",
        widget=forms.TextInput(),
    )
    city = forms.CharField(
        max_length=255, label="City", widget=forms.TextInput(), required=True
    )
    postal_code = forms.CharField(
        max_length=255,
        label="Postal/Zip code",
        widget=forms.TextInput(),
    )
    country = CountryField().formfield(
        label="Country",
        widget=forms.Select(attrs={"placeholder": "Choose your country"}),
    )

{{ cookiecutter.project_slug }}/src/{{ cookiecutter.project_slug }}/billing/views.py
import stripe
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.http.response import HttpResponse, JsonResponse
from django.shortcuts import redirect, render
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_GET, require_http_methods, require_POST
from {{cookiecutter.project_slug}}.billing.forms import UpdateBillingInformationForm
from {{cookiecutter.project_slug}}.model_loaders import get_stripe_customer_model


@never_cache
@require_http_methods(["GET", "POST"])
@login_required
def billing_settings_view(request):
    context = {
        "current_tab": "billing",
    }

    stripe.api_key = settings.STRIPE_SECRET_KEY
    subscription = stripe.Subscription.retrieve(
        request.user.stripe_customer.stripe_subscription_id
    )

    form = UpdateBillingInformationForm(
        request.POST or None,
        initial={
            "name": None,
            "address_line_1": None,
            "address_line_2": None,
            "city": None,
            "postal_code": None,
            "country": None,
        },
    )
    context["form"] = form

    if request.method == "POST":
        if form.is_valid():
            if form.has_changed():
                pass

            return redirect("{{ cookiecutter.project_slug }}-billing:billing-settings")

    return render(request, "billing/pages/billing_settings.html", context)


@csrf_exempt
@require_GET
@login_required
def create_subscribe_checkout_view(request):
    domain_url = request.build_absolute_uri("/")[:-1]
    success = request.GET.get("success", None)
    cancel = request.GET.get("cancel", None)

    stripe.api_key = settings.STRIPE_SECRET_KEY

    try:
        checkout_session = stripe.checkout.Session.create(
            payment_method_types=["card"],
            success_url=domain_url + success + "?subcription_checkout_success=true",
            cancel_url=domain_url + cancel,
            client_reference_id=request.user.uuid,
            customer=request.user.stripe_customer.stripe_customer_id,
            customer_update={
                "address": "auto",
            },
            mode="setup",
        )

        return JsonResponse({"checkout_session_id": checkout_session["id"]})
    except Exception as e:
        return JsonResponse({"error": str(e)})


@require_POST
@login_required
def cancel_subscription_view(request):
    success = request.GET.get("success", None)

    stripe.api_key = settings.STRIPE_SECRET_KEY

    stripe.Subscription.modify(
        request.user.stripe_customer.stripe_subscription_id,
        cancel_at_period_end=True,
    )

    return redirect(success + "?" + "subcription_cancel_success=true")


@require_POST
@login_required
def reactivate_subscription_view(request):
    """
    Reactivate canceled subscription which hasn't reached
    the end of the billing period.

    Note: If the cancellation has already been processed and the
    subscription is no longer active, a new subscription is
    needed for the customer. For this case, use the `create_subscribe_checkout_view`
    endpoint.
    """
    success = request.GET.get("success", None)

    stripe.api_key = settings.STRIPE_SECRET_KEY

    stripe_customer = request.user.stripe_customer

    subscription = stripe.Subscription.retrieve(stripe_customer.stripe_subscription_id)

    if subscription.status.canceled:
        new_subscription = stripe.Subscription.create(
            customer=stripe_customer.stripe_customer_id,
            items=[{"price": settings.STRIPE_PRICE_ID}],
            automatic_tax={"enabled": True},
        )
        stripe_customer.stripe_subscription_id = new_subscription.id
        stripe_customer.save(update_fields=["stripe_subscription_id"])
    else:
        stripe.Subscription.modify(
            subscription.id,
            cancel_at_period_end=False,
            proration_behavior="create_prorations",
            items=[
                {
                    "id": subscription["items"]["data"][0].id,
                    "price": settings.STRIPE_PRICE_ID,
                }
            ],
        )

    return redirect(success + "?" + "subcription_reactivated_success=true")


@require_POST
@login_required
def remove_current_default_payment_method_view(request):
    pass


@csrf_exempt
def stripe_webhook_view(request):
    stripe.api_key = settings.STRIPE_SECRET_KEY
    webhook_secret = settings.STRIPE_WEBHOOK_SECRET
    payload = request.body
    sig_header = request.META["HTTP_STRIPE_SIGNATURE"]
    event = None

    try:
        event = stripe.Webhook.construct_event(payload, sig_header, webhook_secret)
    except ValueError as e:
        return HttpResponse(status=400)
    except stripe.error.SignatureVerificationError as e:
        return HttpResponse(status=400)

    if event["type"] == "checkout.session.completed":
        session = event["data"]["object"]

        # Retrieve setup intent
        setup_intent = stripe.SetupIntent.retrieve(session["setup_intent"])

        # Set payment method as default
        stripe.Customer.modify(
            session["customer"],
            invoice_settings={"default_payment_method": setup_intent.payment_method},
        )

        StripeCustomer = get_stripe_customer_model()
        stripe_customer = StripeCustomer.objects.get(
            stripe_customer_id=session["customer"],
        )

        subscription = stripe.Subscription.retrieve(
            stripe_customer.stripe_subscription_id
        )

        # Check if subscription is still active
        # If subscription is active do nothing
        # If subscription is not active, create new subscription for same customer.

    return HttpResponse(status=200)

{{ cookiecutter.project_slug }}/src/{{ cookiecutter.project_slug }}/billing/templates/billing/forms/update_billing_information_form.html
{% raw %}
    {% for error in form.non_field_errors %}
        <div role="alert" class="mb-2 w-full bg-red-500 py-2 px-4 rounded">
            <span class="text-white">{{ error }}</span>
        </div>
    {% endfor %}
    <div class="sm:col-span-2">
        <div>
            <label for="{{ form.name.id_for_label }}" class="mb-2 label">
                {{ form.name.label }} <span class="text-red-500">*</span>
            </label>
            <input id="id_name"
                   name="name"
                   type="text"
                   value="{{ form.name.value|default_if_none:'' }}"
                   placeholder="{{ form.name.field.widget.attrs.placeholder }}"
                   class="block w-full input">
        </div>
        {% if form.errors.name %}
            <ul class="pt-0.5">
                {% for error in form.errors.name %}<li class="text-sm text-red-500">{{ error|escape }}</li>{% endfor %}
            </ul>
        {% endif %}
    </div>
    <div class="sm:col-span-2">
        <div>
            <label for="{{ form.address_line_1.id_for_label }}" class="mb-2 label">
                {{ form.address_line_1.label }} <span class="text-red-500">*</span>
            </label>
            <p class="mb-2 text-sm font-normal text-gray-700">{{ form.address_line_1.field.help_text }}</p>
            <input id="id_address_line_1"
                   name="address_line_1"
                   type="text"
                   value="{{ form.address_line_1.value|default_if_none:'' }}"
                   placeholder="{{ form.address_line_1.field.widget.attrs.placeholder }}"
                   class="block w-full input">
        </div>
        {% if form.errors.address_line_1 %}
            <ul class="pt-0.5">
                {% for error in form.errors.address_line_1 %}<li class="text-sm text-red-500">{{ error|escape }}</li>{% endfor %}
            </ul>
        {% endif %}
    </div>
    <div class="sm:col-span-2">
        <div>
            <label for="{{ form.address_line_2.id_for_label }}" class="mb-2 label">{{ form.address_line_2.label }}</label>
            <p class="mb-2 text-sm font-normal text-gray-700">{{ form.address_line_2.field.help_text }}</p>
            <input id="id_address_line_2"
                   name="address_line_2"
                   type="text"
                   value="{{ form.address_line_2.value|default_if_none:'' }}"
                   placeholder="{{ form.address_line_2.field.widget.attrs.placeholder }}"
                   class="block w-full input">
        </div>
        {% if form.errors.address_line_2 %}
            <ul class="pt-0.5">
                {% for error in form.errors.address_line_2 %}<li class="text-sm text-red-500">{{ error|escape }}</li>{% endfor %}
            </ul>
        {% endif %}
    </div>
    <div class="sm:col-span-1">
        <div>
            <label for="{{ form.city.id_for_label }}" class="mb-2 label">
                {{ form.city.label }} <span class="text-red-500">*</span>
            </label>
            <input id="id_city"
                   name="city"
                   type="text"
                   value="{{ form.city.value|default_if_none:'' }}"
                   placeholder="{{ form.city.field.widget.attrs.placeholder }}"
                   class="block w-full input">
        </div>
        {% if form.errors.city %}
            <ul class="pt-0.5">
                {% for error in form.errors.city %}<li class="text-sm text-red-500">{{ error|escape }}</li>{% endfor %}
            </ul>
        {% endif %}
    </div>
    <div class="sm:col-span-1">
        <div>
            <label for="{{ form.postal_code.id_for_label }}" class="mb-2 label">{{ form.postal_code.label }}</label>
            <input id="id_postal_code"
                   name="postal_code"
                   type="text"
                   value="{{ form.postal_code.value|default_if_none:'' }}"
                   placeholder="{{ form.postal_code.field.widget.attrs.placeholder }}"
                   class="block w-full input">
        </div>
        {% if form.errors.postal_code %}
            <ul class="pt-0.5">
                {% for error in form.errors.postal_code %}<li class="text-sm text-red-500">{{ error|escape }}</li>{% endfor %}
            </ul>
        {% endif %}
    </div>
    <div class="sm:col-span-1">
        <label for="{{ form.country.id_for_label }}" class="mb-2 label">
            {{ form.country.label }} <span class="text-red-500">*</span>
        </label>
        <div>
            <select id="id_country" name="country" class="block w-full input">
                <option value="" disabled selected>
                    {{ form.country.field.widget.attrs.placeholder }}
                </option>
                {% for x,y in form.fields.country.choices %}
                    <option value="{{ x }}" {% if form.country.value == x %}selected{% endif %}>
                        {{ y }}
                    </option>
                {% endfor %}
            </select>
        </div>
        {% if form.errors.country %}
            <ul class="pt-0.5">
                {% for error in form.errors.country %}<li class="text-sm text-red-500">{{ error|escape }}</li>{% endfor %}
            </ul>
        {% endif %}
    </div>
{% endraw %}